---
- name: Install mariadb for Debian
  apt:
    name:
      - software-properties-common
      - python-mysqldb
      - mariadb-client
      - mariadb-server
    state: present
  when: ansible_os_family == "Debian"

- name: Install mariadb for Centos dists
  block:
    - name: Insall mariadb for Centos
      yum:
        name: 
          - mariadb
          - mariadb-server
          - MySQL-python
        state: present
      when: not ansible_distribution_major_version == "8"

    - name: Insall mariadb for Centos 8
      dnf:
        name: 
          - mariadb
          - mariadb-server
          - MySQL-python
        state: present
      when: ansible_distribution_major_version == "8"
  when: ansible_distribution == "CentOS"

- name: Insall mariadb for fedora 
  dnf:
    name: 
      - mariadb
      - mariadb-server
      - MySQL-python
    state: present
  when:  ansible_distribution == "Fedora"

- name: Enable mariadb
  systemd:
    service: mariadb
    enabled: yes

- name: Start mariadb
  systemd:
    service: mariadb
    state: started
  notify: Restart mariadb