---
- name: Install mariadb for Debian
  apt:
    name:
      - software-properties-common
      - python3-mysqldb
      - mariadb-client
      - mariadb-server
    state: present
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Install mariadb for Centos dists
  block:
    - name: Insall mariadb for Centos
      yum:
        name: 
          - mariadb
          - mariadb-server
          - MySQL-python
        state: present
      changed_when: false
      when: not ansible_distribution_major_version == "8"
    
    - name: Insall mariadb for Centos 8
      yum:
        name: 
          - mariadb
          - mariadb-server
          - MySQL-python3
        state: present
      changed_when: false
      when: ansible_distribution_major_version == "8"
  when: ansible_distribution == "CentOS"

- name: Insall mariadb for Fedora dists
  yum:
    name: 
      - mariadb
      - mariadb-server
      - MySQL-python3
    state: present
  when: ansible_distribution == "Fedora"
  changed_when: false

- name: Enable mariadb
  systemd:
    service: mariadb
    enabled: yes
  changed_when: false

- name: Start mariadb
  systemd:
    service: mariadb
    state: started
  changed_when: false
  notify: Restart mariadb